### ISSUE TITLE
main.go:17:2: cannot find package

### ISSUE THREAD

**Issue by Pois0nEy3** [festie/pornhub-dl#4]
main.go:17:2: cannot find package "github.com/dustin/go-humanize" in any of:

COOL.

**Comment by festie** [comment]
You can download this package by using `go get github.com/dustin/go-humanize`.
After it installs it to your GOPATH, you can build the binary.

**Comment by Pois0nEy3** [comment]
> You can download this package by using `go get github.com/dustin/go-humanize`.
> After it installs it to your GOPATH, you can build the binary.

how to run go script dude ?

**Comment by festie** [comment]
`go run main.go`. Alternatively you can use my precompiled binaries that you can find here, in case you're on windows or mac:
https://github.com/festie/pornhub-dl/releases

You can find more informations about golang here:
https://golang.org/doc/install

**Comment by Pois0nEy3** [comment]
> `go run main.go`. Alternatively you can use my precompiled binaries that you can find here, in case you're on windows or mac:
> https://github.com/festie/pornhub-dl/releases
> 
> You can find more informations about golang here:
> https://golang.org/doc/install

already got it thanks.

pls making script for korean xDDDDDDD


An error occoured while retrieving video details:
Get https://www.pornhub.com/view_video.php?viewkey=ph58c6db7366fb2: read tcp 14.42.180.146:60596->66.254.114.41:443: read: connection reset by peer

fuck korea.

**Comment by festie** [comment]
I would guess that something gets blocked on your end.

**Comment by Pois0nEy3** [comment]
> I would guess that something gets blocked on your end.

no, my network still good, just stupid blocked in korea any porn sites.

so i just changed DPI on my network interface. should can connect to pornhub (mtu 400 default 1500)

**Comment by festie** [comment]
Changing the MTU shouldn't do anything about blocks by your ISP.
Unfortunately there is not much I can do about that on my side.

**Comment by Pois0nEy3** [comment]
> Changing the MTU shouldn't do anything about blocks by your ISP.
> Unfortunately there is not much I can do about that on my side.

cant specify path for download ?

**Comment by festie** [comment]
Have you included the filename into the path? That's what you have to do.

**Comment by Pois0nEy3** [comment]
> Have you included the filename into the path? That's what you have to do.

just made new one myself.

fuck korea
